# This file was generated by GoReleaser. DO NOT EDIT.
class GitBump < Formula
  desc "release to homebrew"
  homepage "https://github.com/s14t284/gitignore-cli"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/s14t284/gitignore-cli/releases/download/v1.0.0/git-bump_darwin_x86_64.tar.gz"
    sha256 "4ad0010ea3edb180a28e9804787ce6170099ff92fd327d9b3b19bf2ef4901eae"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/s14t284/gitignore-cli/releases/download/v1.0.0/git-bump_linux_x86_64.tar.gz"
      sha256 "7540ea8593169309ec3c281db6685717a9d64d615d7604e1f4120a978f84485e"
    end
  end

  def install
    bin.install "gitignore-cli"
  end
end
