# This file was generated by GoReleaser. DO NOT EDIT.
class GitBump < Formula
  desc "release to homebrew"
  homepage "https://github.com/s14t284/gitignore-cli"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/s14t284/gitignore-cli/releases/download/v1.0.0/git-bump_darwin_x86_64.tar.gz"
    sha256 "8e54767efd4baf61e135bbd31f622f90e20e034009c26e20e8b745897868af02"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/s14t284/gitignore-cli/releases/download/v1.0.0/git-bump_linux_x86_64.tar.gz"
      sha256 "6bee8d498fe54ba9173517a17db9347562a8310be346b572817c140b1ba89c90"
    end
  end

  def install
    bin.install "gitignore-cli"
  end
end
