# This file was generated by GoReleaser. DO NOT EDIT.
class GitignoreCli < Formula
  desc "release to homebrew"
  homepage "https://github.com/s14t284/gitignore-cli"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/s14t284/gitignore-cli/releases/download/v1.0.1/git-bump_darwin_x86_64.tar.gz"
    sha256 "4476488fcfd90b48b57c7028a7bdf744be2edf3608a3fd016704fed9b11010dd"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/s14t284/gitignore-cli/releases/download/v1.0.1/git-bump_linux_x86_64.tar.gz"
      sha256 "df6c48dcf79f20a828501a467e196dd7880df8a2b0a7a518f2684c2079cc201c"
    end
  end

  def install
    bin.install "gitignore-cli"
  end
end
