# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitignoreCli < Formula
  desc "release to homebrew"
  homepage "https://github.com/s14t284/gitignore-cli"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/s14t284/gitignore-cli/releases/download/v1.0.2/git-bump_darwin_x86_64.tar.gz"
      sha256 "680ab27745a0c02063f452f8ff698b4e5b88ec51963ba7288bb29f2cb82d4b0f"

      def install
        bin.install "gitignore-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/s14t284/gitignore-cli/releases/download/v1.0.2/git-bump_darwin_arm64.tar.gz"
      sha256 "64a1efcf8ee36050e44f0dc078e499e0262904f62ef2da9b43db30bcdab2fc52"

      def install
        bin.install "gitignore-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/s14t284/gitignore-cli/releases/download/v1.0.2/git-bump_linux_arm64.tar.gz"
      sha256 "971787d2fa1592aaa355e6f28e79f8a572b4eddb80cdc293c9f9cc015741f273"

      def install
        bin.install "gitignore-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/s14t284/gitignore-cli/releases/download/v1.0.2/git-bump_linux_x86_64.tar.gz"
      sha256 "32deba95656ab1236852081b7186a4a3285240098a455e12690e846cfe93c86f"

      def install
        bin.install "gitignore-cli"
      end
    end
  end
end
